server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/ssl/server.pem"
  key: "/ssl/server.key"

token:  # Settings for the tokens.
  issuer: "Auth Service"  # Must match issuer in the Registry config.
  expiration: 900


# Static user map. 
users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$QH.x7wSgRwX/T9LVKwr41e0djC2/2V5uNWPVaIbdssGInvzg.bd8S"
  "": {}  # Allow anonymous (no "docker login") access.

acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]
  # User "test" has full access to ubuntu image but nothing else.
  #  - match: {account: "hussien", name: "ubuntu"}
  #   actions: ["*"]
  #  - match: {account: "test"}
  #  actions: []
  # All logged in users can pull all images.
  #- match: {account: "/.+/"}
  #  actions: ["pull"]
  # Anonymous users can pull "hello-world".
  # ### can pull anything by kennylee ### 
  - match: {account: ""} 
    actions: ["pull"]
  # Access is denied by default.

